language: node_js
services:
- rabbitmq
node_js:
- "lts/*"
before_script:
- npm install -g grunt-cli
deploy:
  provider: npm
  email: henri.bergius@iki.fi
  api_key:
    secure: fRlEzWxpLIho8zz5PbJp0822z8ElSLUXaqAvbvipkYj2jf0KJgurqpcj4Wwj06tELVjmcEfQHzJHZguYwVjdmHmkF7D43r0M7Atni34hoMhLC5LSztb0g28iPGUIHzyu7bQ0KmlAi+X7nyWRxHp4pohlUpIag7UNlPCvDQ3DUnQ=
  on:
    tags: true
    repo: noflo/noflo-amqp
